apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-demo-cron
  namespace: default
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trainer
            image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
            command: ["python", "-c", "import torch; print(torch.rand(2, 2))"]
          restartPolicy: Never
