apiVersion: batch/v1
kind: Job
metadata:
  name: ai-model-training-02
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
        command: ["python", "-c", 
          "import torch, json; \
           result = torch.rand(2, 2).tolist(); \
           log = {'event': 'training_complete', 'status': 'success', 'model': 'demo-v1', 'output': result}; \
           print(json.dumps(log))"]
      restartPolicy: Never
  backoffLimit: 1
